language: python

python:
  - "2.7"

# command to install dependencies
install:
    # notting

# command to run tests
script:

    # setup virtualenv
    - virtualenv django-env
    - source django-env/bin/active
    - pip install -r requirements.txt

    # prepare django
    - python manage.py migrate

after_success:
    # notting



