# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161120_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
